clip_score:
    task: "all"
    fraction_list: [0.5,0.75,0.9]

random_filter:
    task: "all"
    fraction_list: [0.5,0.75,0.9]
  
no_filter:
    task: "all"
    fraction_list: [1]
  
image_based:
    task: "tasks"
    fraction_list: [1]

image_alignment:
    task: "tasks"
    fraction_list: [0.5,0.75,0.9]

match_dist:
    task: "tasks"
    fraction_list: [0.5,0.75,0.9]
    
match_label:
    task: "tasks"
    fraction_list: [1]

