clip_score:
    task: "all"
    fraction_list: [0.75,0.9]

random_filter:
    task: "all"
    fraction_list: [0.75,0.9]
  
no_filter:
    task: "all"
    fraction_list: [1]
  
image_based:
    task: "tasks"
    fraction_list: [1]

image_alignment:
    task: "tasks"
    fraction_list: [0.1,0.25,0.75,0.9]

match_dist:
    task: "tasks"
    fraction_list: [0.1,0.25,0.7,0.9]
    
match_label:
    task: "tasks"
    fraction_list: [1]

tsds:
    task: "tasks"
    fraction_list: [1]

gradmatch:
    task: "tasks"
    fraction_list: [0.25]